sudo: false
language: node_js
node_js:
  - '4.0'
	- '5.0'

before_install:
  - "npm install -g codeclimate-test-reporter"

addons:
  code_climate:
    repo_token: 9396fc7949652a2bc8d9a501379d757d9f814bdd0316e47e96dc7564faa10c35

script:
  - "npm run coverage"

after_script:
  - "cat ./coverage/lcov.info | codeclimate-test-reporter"